Add README with instructions to install
FuelLabs/design-system pull request #10
Opened 2022-05-04 20:52 UTC by pixelsbyeryc

**Closes:** #1 

Adding `README.md` with the following sections:
1. Banner
2. Getting Started
    1. Project Installation
    2. Running the Development Environment
    3. Configuring Node and NVM
3. `draft` Contributing
4. `draft` License

2022-05-04 20:59 UTC, biantris approved these changes
nice

2022-05-04 21:58 UTC, pedronauck requested changes

2022-05-04 21:58 UTC, pedronauck commented on README.md
> +Whenever you add, remove, or alter a component's css annotation metadata, you'll need to restart Storybook to see those changes.
This is not mandatory, you don't need to restart Storybook for every change, it has a cool fast refresh. Do you need this just if change Storybook bundler configurations (living inside `.storybook` folder)

2022-05-04 21:58 UTC, pedronauck commented on README.md
> +We reccomend you use the latest stable version of node on your computer.
recommend*

2022-05-05 04:41 UTC, pedronauck approved these changes

2022-05-05 04:42 UTC, merged